"""reconciliacao de pessoas PM antes da promocao (D-023)

Revision ID: 184c8d2a95b7
Revises: f61c909abae0
Create Date: 2026-09-14 12:57:26.053383

Nota: as duas colunas NOT NULL adicionadas a `staging_project_records`
(tabela já existente, potencialmente não vazia) levam `server_default`
explícito — sem isso, tanto SQLite como PostgreSQL recusam-se a adicionar
uma coluna NOT NULL a uma tabela com linhas existentes. O autogenerate não
inclui isto sozinho; adicionado à mão.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # necessário para o tipo de coluna portável app.db.GUID()


# revision identifiers, used by Alembic.
revision: str = '184c8d2a95b7'
down_revision: Union[str, Sequence[str], None] = 'f61c909abae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_reconciliation_items',
    sa.Column('raw_name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('candidate_person_ids_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_person_id', app.db.GUID(), nullable=True),
    sa.Column('resolved_by_person_id', app.db.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['resolved_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('staging_project_records', sa.Column('pm_name_raw', sa.String(length=256), nullable=True))
    op.add_column(
        'staging_project_records',
        sa.Column('candidate_person_ids_json', sa.Text(), nullable=False, server_default=sa.text("'[]'")),
    )
    op.add_column(
        'staging_project_records',
        # sa.false() renderiza corretamente em ambos os motores (0 em
        # SQLite, FALSE em PostgreSQL) — nunca um literal de texto fixo.
        sa.Column('pm_explicitly_unassigned', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staging_project_records', 'pm_explicitly_unassigned')
    op.drop_column('staging_project_records', 'candidate_person_ids_json')
    op.drop_column('staging_project_records', 'pm_name_raw')
    op.drop_table('person_reconciliation_items')
    # ### end Alembic commands ###
