"""mvp dashboard: tarefas, ferias/ausencias, aniversario (data de nascimento)

Revision ID: 207faad55b86
Revises: 67150240f450
Create Date: 2026-09-15 11:05:39.675186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # necessário para o tipo de coluna portável app.db.GUID()


# revision identifiers, used by Alembic.
revision: str = '207faad55b86'
down_revision: Union[str, Sequence[str], None] = '67150240f450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absences',
    sa.Column('person_id', app.db.GUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_person_id', app.db.GUID(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('project_id', app.db.GUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assigned_to_person_id', app.db.GUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_person_id', app.db.GUID(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_history',
    sa.Column('task_id', app.db.GUID(), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_person_id', app.db.GUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('people', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'birth_date')
    op.drop_table('task_history')
    op.drop_table('tasks')
    op.drop_table('absences')
    # ### end Alembic commands ###
