"""venda do excedente: surplus contract

Revision ID: 9d75fdc41128
Revises: b9b2ef89a44b
Create Date: 2026-09-17 14:26:17.545832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # necessário para o tipo de coluna portável app.db.GUID()


# revision identifiers, used by Alembic.
revision: str = '9d75fdc41128'
down_revision: Union[str, Sequence[str], None] = 'b9b2ef89a44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surplus_contracts',
    sa.Column('project_id', app.db.GUID(), nullable=True),
    sa.Column('internal_reference_raw', sa.String(length=128), nullable=True),
    sa.Column('commercializer', sa.String(length=256), nullable=True),
    sa.Column('contract_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('import_batch_id', app.db.GUID(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['field_import_batches.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surplus_contracts')
    # ### end Alembic commands ###
