"""importacao de notas iniciais: field import batch, record, conflict

Revision ID: b9b2ef89a44b
Revises: 65bf12876b1e
Create Date: 2026-09-17 12:36:38.821663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # necessário para o tipo de coluna portável app.db.GUID()


# revision identifiers, used by Alembic.
revision: str = 'b9b2ef89a44b'
down_revision: Union[str, Sequence[str], None] = '65bf12876b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_import_batches',
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('source_file_hash', sa.String(length=128), nullable=False),
    sa.Column('form_version', sa.String(length=32), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_by_person_id', app.db.GUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('applied_by_person_id', app.db.GUID(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['started_by_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_hash', name='uq_field_import_source_hash')
    )
    op.create_table('field_import_records',
    sa.Column('batch_id', app.db.GUID(), nullable=False),
    sa.Column('target_project_id', app.db.GUID(), nullable=True),
    sa.Column('is_new_project', sa.Boolean(), nullable=False),
    sa.Column('match_strategy', sa.String(length=32), nullable=False),
    sa.Column('candidate_project_ids_json', sa.Text(), nullable=False),
    sa.Column('mapped_fields_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('promoted_project_id', app.db.GUID(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['field_import_batches.id'], ),
    sa.ForeignKeyConstraint(['promoted_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_import_conflicts',
    sa.Column('record_id', app.db.GUID(), nullable=False),
    sa.Column('target_entity', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=False),
    sa.Column('resolved_by_person_id', app.db.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['field_import_records.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_import_conflicts')
    op.drop_table('field_import_records')
    op.drop_table('field_import_batches')
    # ### end Alembic commands ###
